package extremeblocks;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.EnumHelper;
import com.hk.testing.util.BlockCustom;
import com.hk.testing.util.CustomTab;
import com.hk.testing.util.ItemCustom;
import com.hk.testing.util.ItemToolSet.ItemCSword;
import com.hk.testing.util.MPUtil;
import extremeblocks.blocks.BlockCement;
import extremeblocks.blocks.BlockConsole;
import extremeblocks.blocks.BlockDriedSapling;
import extremeblocks.blocks.BlockDrill;
import extremeblocks.blocks.BlockFuseBlock;
import extremeblocks.blocks.BlockGameFloor;
import extremeblocks.blocks.BlockGameFloor.GameBlockType;
import extremeblocks.blocks.BlockHydrant;
import extremeblocks.blocks.BlockLantern;
import extremeblocks.blocks.BlockPowderKeg;
import extremeblocks.blocks.BlockRewardBlock;
import extremeblocks.blocks.BlockTrash;
import extremeblocks.blocks.BlockVendingMachine;
import extremeblocks.blocks.BlockXrayBlock;
import extremeblocks.blocks.abstractblocks.BlockCompact;
import extremeblocks.blocks.abstractblocks.BlockOre;
import extremeblocks.blocks.abstractblocks.BlockSided;
import extremeblocks.items.ItemBackpack;
import extremeblocks.items.ItemCellphone;
import extremeblocks.items.ItemCounter;
import extremeblocks.items.ItemExtractor;
import extremeblocks.items.ItemFuse;
import extremeblocks.items.ItemNotes;
import extremeblocks.items.ItemReturner;

public class Init
{
	public static final String MODID = "extremeblocks";
	public static CreativeTabs tab_ebOres = new CustomTab("EB Ores");
	public static CreativeTabs tab_lightedBlocks = new CustomTab("Lighted Blocks");
	public static CreativeTabs tab_mainBlocks = new CustomTab("Main Blocks");
	public static CreativeTabs tab_misc = new CustomTab("Miscellaneous");
	public static CreativeTabs tab_fakeFloors = new CustomTab("Fake Floors");
	public static CreativeTabs tab_mainItems = new CustomTab("Main Items");
	public static CreativeTabs tab_tools = new CustomTab("Tools");

	public static ToolMaterial TRINQUANTIUM = EnumHelper.addToolMaterial("Trinquantium", 4, 2368, 10.0F, 4.0F, 15);
	public static ToolMaterial BRONZE = EnumHelper.addToolMaterial("Bronze", 2, 328, 5.0F, 3.0F, 12);
	public static ToolMaterial SILVER = EnumHelper.addToolMaterial("Silver", 0, 13, 6.0F, 8.0F, 7);
	public static ToolMaterial GLESTER = EnumHelper.addToolMaterial("Glester", 0, 71, 9.0F, 0.0F, 9);
	public static ToolMaterial DELVLISH = EnumHelper.addToolMaterial("Delvlish", 0, 71, 0.0F, 5.0F, 4);
	public static ToolMaterial METEORITE = EnumHelper.addToolMaterial("Meteorite", 3, 2306, 6.0F, 6.0F, 4);
	public static ToolMaterial SAPPHIRE = EnumHelper.addToolMaterial("Sapphire", 3, 1909, 7.0F, 7.0F, 14);
	public static ToolMaterial ONYX = EnumHelper.addToolMaterial("Onyx", 2, 514, 4.0F, 9.0F, 17);
	public static ToolMaterial FLUORITE = EnumHelper.addToolMaterial("Fluorite", 2, 392, 5.0F, 2.0F, 7);
	public static ToolMaterial DIAMOND = EnumHelper.addToolMaterial("Emerald", 4, 4096, 12.0F, 5.0F, 15);

	public static final Item extreme_blocks = new ItemCustom("EB", null).setTextureName(MODID + ":EB");
	public static final Item gold_coin = new ItemCustom("Gold Coin", tab_mainItems).setTextureName(MODID + ":gold_coin");
	public static final Item glester_rock = new ItemCustom("Glester Rock", tab_mainItems).setTextureName(MODID + ":glester_rock");
	public static final Item delvlish_crystal = new ItemCustom("Delvlish Crystal", tab_mainItems).setTextureName(MODID + ":delvlish_crystal");
	public static final Item silver_ingot = new ItemCustom("Silver Ingot", tab_mainItems).setTextureName(MODID + ":silver_ingot");
	public static final Item trinquantium_ingot = new ItemCustom("Trinquantium Ingot", tab_mainItems).setTextureName(MODID + ":trinquantium_ingot");
	public static final Item crushed_stone = new ItemCustom("Crushed Stone", tab_mainItems).setTextureName(MODID + ":crushed_stone");
	public static final Item bronze_medal = new ItemCustom("Bronze Medal", tab_mainItems).setTextureName(MODID + ":bronze_medal");
	public static final Item silver_medal = new ItemCustom("Silver Medal", tab_mainItems).setTextureName(MODID + ":silver_medal");
	public static final Item gold_medal = new ItemCustom("Gold Medal", tab_mainItems).setTextureName(MODID + ":gold_medal");
	public static final Item trinquantium_medal = new ItemCustom("Trinquantium Medal", tab_mainItems).setTextureName(MODID + ":trinquantium_medal");
	public static final Item copper = new ItemCustom("Copper", tab_mainItems).setTextureName(MODID + ":copper");
	public static final Item tin = new ItemCustom("Tin", tab_mainItems).setTextureName(MODID + ":tin");
	public static final Item copper_and_tin_lump = new ItemCustom("Copper and Tin Lump", tab_mainItems).setTextureName(MODID + ":copper_tin_lump");
	public static final Item bronze_ingot = new ItemCustom("Bronze Ingot", tab_mainItems).setTextureName(MODID + ":bronze_ingot");
	public static final Item sap = new ItemCustom("Sap", tab_mainItems).setTextureName(MODID + ":sap");
	public static final Item extractor = new ItemExtractor();
	public static final Item cellphone = new ItemCellphone();
	public static final Item plastic = new ItemCustom("Plastic", tab_mainItems).setTextureName(MODID + ":plastic");
	public static final Item chip = new ItemCustom("Chip", tab_mainItems).setTextureName(MODID + ":chip");
	public static final Item bone_shard = new ItemCustom("Bone Shard", tab_mainItems).setTextureName(MODID + ":bone_shard");
	public static final Item bone_sword = new ItemCSword(ToolMaterial.GOLD);
	public static final Item wrench = new ItemCustom("Wrench", tab_mainItems).setTextureName(MODID + ":wrench");
	public static final Item pipes = new ItemCustom("Pipes", tab_mainItems).setTextureName(MODID + ":pipes");
	public static final Item pipe = new ItemCustom("Pipe", tab_mainItems).setTextureName(MODID + ":pipe");
	public static final Item backpack = new ItemBackpack();
	public static final Item light = new ItemCustom("Light", tab_mainItems).setTextureName(MODID + ":light");
	public static final Item limestone = new ItemCustom("Limestone", tab_mainItems).setTextureName(MODID + ":limestone");
	public static final Item core_chip = new ItemCustom("Core Chip", tab_mainItems).setTextureName(MODID + ":core_chip");
	public static final Item game_remote = new ItemCustom("Game Remote", tab_mainItems).setTextureName(MODID + ":game_remote");
	public static final Item returner = new ItemReturner();
	public static final Item counter = new ItemCounter();
	public static final Item notes = new ItemNotes(true);
	public static final Item notes1 = new ItemNotes(false);
	public static final Item meteorite_shards = new ItemCustom("Meteorite Shards", tab_mainItems).setTextureName(MODID + ":meteorite_shards");
	public static final Item meteor = new ItemCustom("Meteor", tab_mainItems).setTextureName(MODID + ":meteorite");
	public static final Item fluorite = new ItemCustom("Fluorite", tab_mainItems).setTextureName(MODID + ":fluorite");
	public static final Item sapphire = new ItemCustom("Sapphire", tab_mainItems).setTextureName(MODID + ":sapphire");
	public static final Item onyx = new ItemCustom("Onyx", tab_mainItems).setTextureName(MODID + ":onyx");
	public static final Item fuse = new ItemFuse();

	public static final Block glester_ore = new BlockOre("Glester Ore").setDrop(glester_rock);
	public static final Block silver_ore = new BlockOre("Silver Ore");
	public static final Block trinquantium_ore = new BlockOre("Trinquantium Ore");
	public static final Block copper_ore = new BlockOre("Copper Ore").setDrop(copper);
	public static final Block tin_ore = new BlockOre("Tin Ore").setDrop(tin);
	public static final Block delvlish_ore = new BlockOre("Delvlish Ore").setDrop(delvlish_crystal);
	public static final Block compact_stone = new BlockCustom(Material.rock, "Compact Stone").setHardness(3.0F).setCreativeTab(tab_mainBlocks).setBlockTextureName(MODID + ":Compact Stone");
	public static final Block silver_block = new BlockCompact("Silver Block");
	public static final Block bronze_block = new BlockCompact("Bronze Block");
	public static final Block trinquantium_block = new BlockCompact("Trinquantium Block");
	public static final Block xray_block = new BlockXrayBlock(true);
	public static final Block xray_block_un = new BlockXrayBlock(false);
	public static final Block cement_wall = new BlockCement(true);
	public static final Block plaster_wall = new BlockCustom(Material.rock, "Plaster Wall").setBlockTextureName(MODID + ":plasterwall").setCreativeTab(tab_mainBlocks);
	public static final Block weak_cement_wall = new BlockCement(false);
	public static final Block emptied_log = new BlockSided(Material.wood, "Emptied Log", "emptiedlog");
	public static final Block bone_dirt = new BlockCustom(Material.ground, "Bone Dirt").setDrop(bone_shard).setBlockTextureName(MODID + ":bone_dirt").setCreativeTab(tab_mainBlocks);
	public static final Block waste = new BlockCustom(Material.lava, "Waste").irregular().setBounds(0.0F, 0.0F, 0.0F, 1.0F, 0.2F, 1.0F).setBlockTextureName(MODID + ":waste").setCreativeTab(tab_misc);
	public static final Block fire_hydrant = new BlockHydrant();
	public static final Block lantern = new BlockLantern();
	public static final Block stone_pillar = new BlockSided(Material.rock, "Stone Pillar", "stonepillar");
	public static final Block trash = new BlockTrash();
	public static final Block vending_machine = new BlockVendingMachine();
	public static final Block dried_sapling = new BlockDriedSapling();
	public static final Block limestone_block = new BlockCustom(Material.rock, "Block of Limestone").setCreativeTab(tab_mainBlocks).setBlockTextureName(MODID + ":limestoneblock");
	public static final Block marble = new BlockCustom(Material.glass, "Marble").setCreativeTab(tab_mainBlocks).setBlockTextureName(MODID + ":marbleblock");
	public static final Block limestone_ore = new BlockOre("Limestone Ore").setDrop(limestone);
	public static final Block fake_sand = new BlockCustom(Material.ground, "Fake Sand").setCreativeTab(tab_misc).setBlockTextureName("sand");
	public static final Block fake_gravel = new BlockCustom(Material.ground, "Fake Gravel").setCreativeTab(tab_misc).setBlockTextureName("gravel");
	public static final Block drill = new BlockDrill(true);
	public static final Block drill_pole = new BlockDrill(false);
	public static final Block red_game_floor = new BlockGameFloor(GameBlockType.Red);
	public static final Block yellow_game_floor = new BlockGameFloor(GameBlockType.Yellow);
	public static final Block green_game_floor = new BlockGameFloor(GameBlockType.Green);
	public static final Block blue_game_floor = new BlockGameFloor(GameBlockType.Blue);
	public static final Block spread_game_block = new BlockGameFloor(GameBlockType.Spread);
	public static final Block console = new BlockConsole();
	public static final Block reward_block = new BlockRewardBlock();
	public static final Block onyx_ore = new BlockOre("Onyx Ore").setDrop(onyx);
	public static final Block meteorite = new BlockOre("Meteorite").setDrop(meteorite_shards);
	public static final Block fluorite_ore = new BlockOre("Fluorite Ore").setDrop(fluorite);
	public static final Block sapphire_ore = new BlockOre("Sapphire Ore").setDrop(sapphire);
	public static final Block fuse_block = new BlockFuseBlock();
	public static final Block powder_keg = new BlockPowderKeg();

	public static void addRecipes()
	{
		MPUtil.addRecipe(new ItemStack(counter), "X#", 'X', core_chip, '#', Blocks.wooden_button);
		MPUtil.addRecipe(new ItemStack(counter), "X#", 'X', core_chip, '#', Blocks.stone_button);
		MPUtil.addRecipe(new ItemStack(console), "XXX", "X#X", "XXB", 'X', plastic, '#', core_chip, 'B', light);
		MPUtil.addRecipe(new ItemStack(drill), "XXX", "#B#", " # ", 'X', Items.iron_ingot, '#', Items.diamond, 'B', Items.redstone);
		MPUtil.addRecipe(new ItemStack(fake_gravel), "XX", 'X', Blocks.gravel);
		MPUtil.addRecipe(new ItemStack(fake_sand), "XX", 'X', Blocks.sand);
		MPUtil.addRecipe(new ItemStack(fire_hydrant), " # ", "#X#", "XBX", '#', Items.iron_ingot, 'X', pipes, 'B', Items.flint);
		MPUtil.addRecipe(new ItemStack(vending_machine), "##B", "#X#", "###", '#', Items.iron_ingot, 'X', core_chip, 'B', light);
		MPUtil.addRecipe(new ItemStack(trash), "##", "##", '#', Items.iron_ingot);
		MPUtil.addRecipe(new ItemStack(limestone_block), "##", "##", '#', limestone);
		MPUtil.addRecipe(new ItemStack(game_remote), "###", "#X#", "# #", '#', plastic, 'X', chip);
		MPUtil.addRecipe(new ItemStack(light), "###", "#X#", "###", '#', Items.redstone, 'X', chip);
		MPUtil.addRecipe(new ItemStack(core_chip), "###", '#', chip);
		MPUtil.addRecipe(new ItemStack(stone_pillar), "##", "##", "##", '#', Blocks.stone);
		MPUtil.addRecipe(new ItemStack(lantern), "#", "#", '#', Blocks.glass);
		MPUtil.addRecipe(new ItemStack(Blocks.planks, 2), "#", '#', emptied_log);
		MPUtil.addRecipe(new ItemStack(backpack), "###", "#X#", "###", '#', Items.leather, 'X', Items.ender_eye);
		MPUtil.addRecipe(new ItemStack(pipes), "##", "##", '#', pipe);
		MPUtil.addRecipe(new ItemStack(wrench), "# #", "###", " # ", '#', Items.iron_ingot);
		MPUtil.addRecipe(new ItemStack(pipe), "###", '#', Items.iron_ingot);
		MPUtil.addRecipe(new ItemStack(bone_sword), "#", "#", '#', bone_shard);
		MPUtil.addRecipe(new ItemStack(Items.bone), "##", "##", '#', bone_shard);
		MPUtil.addRecipe(new ItemStack(plastic, 2), "##", "##", '#', sap);
		MPUtil.addRecipe(new ItemStack(chip), "##", "##", '#', Items.redstone);
		MPUtil.addRecipe(new ItemStack(cellphone), "##X", "#B#", "###", '#', plastic, 'X', Items.redstone, 'B', chip);
		MPUtil.addRecipe(new ItemStack(extractor), "#X#", '#', Blocks.stone, 'X', Blocks.lever);
		MPUtil.addRecipe(new ItemStack(crushed_stone, 5), "#", "#", '#', Blocks.stone);
		MPUtil.addRecipe(new ItemStack(xray_block_un), "XBX", "B#B", "XBX", '#', Blocks.torch, 'B', Items.diamond, 'X', trinquantium_ingot);
		MPUtil.addRecipe(new ItemStack(xray_block), "XBX", "B#B", "XBX", '#', xray_block_un, 'B', delvlish_crystal, 'X', glester_rock);
		MPUtil.addRecipe(new ItemStack(gold_coin, 3), " # ", "###", " # ", '#', Items.gold_nugget);
		MPUtil.addRecipe(new ItemStack(bronze_medal, 3), " # ", "###", "###", '#', bronze_ingot);
		MPUtil.addRecipe(new ItemStack(silver_medal, 3), " # ", "###", "###", '#', silver_ingot);
		MPUtil.addRecipe(new ItemStack(gold_medal, 3), " # ", "###", "###", '#', Items.gold_ingot);
		MPUtil.addRecipe(new ItemStack(copper_and_tin_lump, 3), "#X#", "X#X", '#', copper, 'X', tin);
		MPUtil.addRecipe(new ItemStack(copper_and_tin_lump, 3), "#X#", "X#X", 'X', copper, '#', tin);
		MPUtil.addRecipe(new ItemStack(trinquantium_medal, 3), " # ", "###", "###", '#', trinquantium_ingot);
		MPUtil.addRecipe(new ItemStack(weak_cement_wall), "###", "#X#", "###", '#', crushed_stone, 'X', Items.water_bucket);
		MPUtil.addRecipe(new ItemStack(fuse), "##", '#', Items.gunpowder);
		MPUtil.addRecipe(new ItemStack(powder_keg), "#X#", "#X#", '#', Items.gunpowder, 'X', fuse);
		MPUtil.addRecipe(new ItemStack(meteor), "##", "##", '#', meteorite_shards);

		MPUtil.addCompactRecipe(new ItemStack(limestone_block), limestone);
		MPUtil.addCompactRecipe(new ItemStack(silver_block), silver_ingot);
		MPUtil.addCompactRecipe(new ItemStack(bronze_block), bronze_ingot);
		MPUtil.addCompactRecipe(new ItemStack(trinquantium_block), trinquantium_ingot);
		MPUtil.addCompactRecipe(new ItemStack(plaster_wall), plastic);
		MPUtil.addCompactRecipe(new ItemStack(compact_stone), Blocks.stone);
		MPUtil.addCompactRecipe(new ItemStack(waste), Items.slime_ball);

		MPUtil.addSmeltingRecipe(new ItemStack(trinquantium_ore), new ItemStack(trinquantium_ingot), 4.0F);
		MPUtil.addSmeltingRecipe(new ItemStack(silver_ore), new ItemStack(silver_ingot), 2.0F);
		MPUtil.addSmeltingRecipe(new ItemStack(copper_and_tin_lump), new ItemStack(bronze_ingot), 3.0F);
		MPUtil.addSmeltingRecipe(new ItemStack(weak_cement_wall), new ItemStack(cement_wall), 3.0F);
		MPUtil.addSmeltingRecipe(new ItemStack(limestone_block), new ItemStack(marble), 3.0F);
	}
}
